### ISSUE TITLE
Errors following Flask2 upgrade

### ISSUE THREAD

**Issue by russellvt** [russellvt/hockey-info#2]
Following the upgrade to Flask2 (See [flask2](/russellvt/hockey-info/tree/flask2) branch / commit ae7dccabf3b2c51f7324e040a25cdf78d3b15b86), it seems we have other "code breaks."

```
...
2023-04-27
2023-04-28
2023-04-29
[2023-04-29 06:26:13,608] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "~/projects/hockey/hockey-info/app.py", line 46, in show_playoffs
    playoff_msg.append({'matchup': series['names']['matchupShortName'], 'status': series['currentGame']['seriesSummary']['seriesStatus']})
KeyError: 'seriesStatus'
172.16.72.181 - - [29/Apr/2023 06:26:13] "GET / HTTP/1.1" 500 -
[2023-04-29 06:26:14,498] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "~/projects/hockey/hockey-info/venv-hockey/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "~/projects/hockey/hockey-info/app.py", line 20, in favicon
    return send_from_directory(os.apth.join(app.root_path, 'static'),
NameError: name 'os' is not defined
```

I *suspect* that the first issue (ie. when data is imported) is due to a lack of data for "today," which hasn't yet happened (ie. missing/expected data).

The second issue appears to be a typo that's somehow not previously been "found" (previously unreachable code path, or uncommon issue - possibly due to the previous missing data?)

**Comment by russellvt** [comment]
Fixed (worked around) in 37f13079f4d06bda3ca5b236e685b5ff5f79fb6f,
